### ISSUE TITLE
Capacitor

### ISSUE THREAD

**Issue by sandstrom** [wonderpush/wonderpush-cordova-sdk#2]
Do you have plans to support Capacitor in WonderPush? 

It's a spiritual successor to Cordova, built by Ionic. With some adjustments this SDK should be fairly easy to adapt so that it'll work with Capacitor.

More details here:
https://capacitor.ionicframework.com/docs/plugins

**Comment by timomayer** [comment]
any news on this @ofavre . this would be highly appreciated since Capacitor is more or less the way to go now.

**Comment by ofavre** [comment]
Hi,

We support Capacitor since [v3.0.10](https://github.com/wonderpush/wonderpush-cordova-sdk/releases/tag/v3.0.10). We should have closed this ticket then.

[Here is the quick start guide](https://docs.wonderpush.com/docs/mobile-push-notifications-ionic) for getting you started with Ionic with Capacitor. (The previous guide for Ionic with Cordova has moved right underneath it for projects still using that setup.)

Best,
